name: Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Site
        run: npm run build
        env:
          # Gatsby build-time environment variables
          GATSBY_GA_TRACKING_ID: ${{ secrets.GATSBY_GA_TRACKING_ID }}
          GATSBY_SQUARE_APP_ID: ${{ secrets.GATSBY_SQUARE_APP_ID }}
          GATSBY_SQUARE_LOCATION_ID: ${{ secrets.GATSBY_SQUARE_LOCATION_ID }}
          SITE_URL: https://tagteamprints.com
          NODE_ENV: production
          # S&S API credentials for build-time data fetching
          SNS_API_USERNAME: ${{ secrets.SNS_API_USERNAME }}
          SNS_API_KEY: ${{ secrets.SNS_API_KEY }}

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './public'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy from GitHub Actions'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
